#!/bin/bash

elf="$1"
if [ -z "$elf" ]; then
	echo usage: \`genhooks \<elf\>\`
	exit
fi

symtbl="$(mktemp)"
mips64-nm "$elf" | awk '(/^[0-9A-Za-z_ ]*$/) {printf "sym_%s=0x%s\n",$3,substr($1,length($1)-7)}' >"$symtbl"
. "$symtbl"
rm -f "$symtbl"

gsc16()
{
    addr="$(printf "%d" "$1")"
    addr="$(expr "$addr" % 16777216 + 2164260864)" # addr = addr & 0x00FFFFFF | 0x81000000
    val="$(printf "%d" "$2")"
    val="$(expr "$val" % 65536)" # val = val & 0xFFFF
    printf "%08X %04X\n" "$addr" "$val"
}

genhook()
{
    addr="$(printf "%d" "$1")"
    tmp="$(mktemp)"
    echo ".set noreorder; .set noat; $2" | mips64-as - -o "$tmp"
    mips64-readelf -x .text "$tmp" | grep "0x[0-9A-Fa-f]\{8\}" | grep -o " [0-9A-Fa-f]\{8\}" |
    while read -r line; do
        gsc16 "$addr" "0x`echo "$line" | sed -e "s/\(....\)..../\1/"`"
        addr="$(expr "$addr" + 2)"
        gsc16 "$addr" "0x`echo "$line" | sed -e "s/....\(....\)/\1/"`"
        addr="$(expr "$addr" + 2)"
    done
    rm -f "$tmp"
}

genhook "$sym_update_hook" "jal $sym_fp_update_entry;"
genhook "$sym_draw_hook" "jal $sym_fp_draw_entry;"
genhook "$sym_after_draw_hook" "jal $sym_fp_after_draw_entry;"
genhook "$sym_update_camera_mode_6_hook" "jal $sym_fp_update_camera_mode_6;"
genhook "$sym_update_player_input_rom_hook" "jal $sym_fp_update_input;"
echo "81104DCC 2404"
echo "81104DCE 2073"
echo "81097F90 5249"
echo "81097F92 5020"
echo "81097F94 424F"
echo "81097F96 5A4F" 
echo "81097F98 204C" 
echo "81097F9A 4C4C"
echo "81097F9C 4C4C"
echo "81097F9E 4C4C"
echo "81097FA0 4C4C"
echo "81097FA2 4C4C"
echo "81097FA4 4C00"
echo "8109810D 5241"
echo "8109810F 5449"
echo "80098111 004F"
echo 81190C38 2907
echo 81190C3A 4C4C
echo 81190C3C F748
echo 81190C3E 4156
echo 81190C40 45F7
echo 81190C42 5548
echo 81190C44 4848
echo 81190C46 4848
echo 81190C48 4848
echo 81190C4A 4848
echo 80190C4C 0048
genhook "0x801139B8" "jal $sym_fp_goto_map;"
genhook "0x801139D8" "jal $sym_fp_goto_map;"
genhook "0x801139F8" "jal $sym_fp_goto_map;"